
create table ESTUDANTES
(
    matricula int primary key not null,
    nome_estudante varchar(200) not null,
    foreign key (codigo_curso) references CUSROS(codigo)
)

create table CURSOS
(
    codigo int primary key not null,
    nome_curso varchar(200) not null
)


CREATE TABLE CARROS
(
    CODIGO INT NOT NULL PRIMARY KEY,
    MARCA VARCHAR(100) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    ANO INT(4) NOT NULL,
    PRECO DECIMAL NOT NULL,
    OBSERVACAO VARBINARY(max) NULL
)

CREATE TABLE CLIENTES
(
    CODIGO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    CELULAR varchar(15) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARBINARY(MAX) NULL
)

CREATE TABLE VENDEDORES
(
    CODIGO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    HORARIO_TRABALHO VARCHAR(20) NOT NULL,
    SALARIO DECIMAL(10) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARBINARY(max) NULL
)

CREATE TABLE HIST_CARROS
(
    CODIGO INT PRIMARY KEY NOT NULL,
    FOREIGN KEY (CODIGO_CARRO) REFERENCES CARROS(CODIGO),
    FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO),
    PRECO DECIMAL(10) NOT NULL,
    ANO INT(4) NOT NULL,
    MARCA VARCHAR(100) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    OBSERVACAO VARBINARY(max) NULL
)